### ISSUE TITLE
binary_sensor.snowtire_x

### ISSUE THREAD

**Issue by JamesDenby** [Limych/ha-snowtire#22]
**Environment**

- Home Assistant Core release with the issue:  core-2021.4.4
- This custom component release with the issue:  v1.2.1
- Last working this custom component release (if known):  unknown
- Operating environment (Home Assistant/Supervisor/Docker/venv):  Home Assistant supervisor-2021.04.0

**Describe the bug**

**Configuration.yaml**
```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#  zeroconf: # Depricated 10 Jun 20

# Application Discovery of items
discovery:
#  ignore:
#  enable:

# Enable Python Scripts to run (Shelly H&T)
#python_script:


# Need this even though I have default_config:
frontend:
  themes: !include_dir_merge_named themes

# Add customization information:
homeassistant:
  customize: !include customize.yaml

# Needed to assess health of system
system_health:

# Config for mobile phone app
mobile_app:
cloud:
ios:
stream:

# FFMPEG for ONVIF camera
ffmpeg:

# Text to speech
tts:
  - platform: google_translate

# Control and limit size of database

# Lutron Caseta Control
lutron_caseta:
  host: !secret loc
  keyfile: /ssl/lutron/caseta.key
  certfile: /ssl/lutron/caseta.crt
  ca_certs: /ssl/lutron/caseta-bridge.crt


# Netatmo detail required before adding in Integrations
netatmo:
  client_id: !secret client_id
  client_secret: !secret client_secret


# Debug
logger:
  default: warning
  logs:
    homeassistant.components.python_script: debug
    homeassistant.components.automation: info
    custom_components.snowtire: debug

amcrest: !include video_a.yaml
automation: !include_dir_list automation/
#automation: !include automations.yaml
binary_sensor: !include bsensor.yaml
camera: !include video.yaml
garbage_collection: !include trash.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
input_boolean: !include boolean.yaml
input_select: !include inselect.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
sonoff: !include sonoff.yaml
weather: !include weather.yaml

Add your configs here if any.

```

**Steps to Reproduce**

Searched entities for binary_sensor.snowtire. The resulting list showed several

**Expected behavior**

I expected there to be only one binary_sensor.snowtire

**Debug log**

```text

Add your logs here.

```2021-04-13 08:31:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration gismeteo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration snowtire which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-13 08:31:14 INFO (MainThread) [custom_components.snowtire.binary_sensor] 
-------------------------------------------------------------------
Snowtire Sensor
Version: 1.2.1
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-snowtire/issues
-------------------------------------------------------------------

2021-04-13 08:32:14 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Current temperature -3.0°C
2021-04-13 08:32:14 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Inspect weather forecast from 2021-04-13 till 2021-04-21
2021-04-13 08:32:14 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Temperature vector: [-3.0, 5, -2, 8, -1, 14, 0, 15, 2, 18, 0, 12]
2021-04-13 08:32:26 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Current temperature -3.0°C
2021-04-13 08:32:26 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Inspect weather forecast from 2021-04-13 till 2021-04-21
2021-04-13 08:32:26 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Temperature vector: [-3.0, 5, -2, 8, -1, 14, 0, 15, 2, 18, 0, 12]
2021-04-13 08:32:26 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Too cold temperature detected!
2021-04-13 08:32:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Current temperature -3.0°C
2021-04-13 08:32:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Inspect weather forecast from 2021-04-13 till 2021-04-21
2021-04-13 08:32:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Temperature vector: [-3.0, 5, -2, 8, -1, 14, 0, 15, 2, 18, 0, 12]
2021-04-13 08:32:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Too cold temperature detected!
2021-04-13 08:33:22 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Current temperature -3.0°C
2021-04-13 08:33:22 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Inspect weather forecast from 2021-04-13 till 2021-04-21
2021-04-13 08:33:22 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Temperature vector: [-3.0, 5, -2, 8, -1, 14, 0, 15, 2, 18, 0, 12]
2021-04-13 08:33:22 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Too cold temperature detected!
2021-04-13 08:33:44 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'Amcrest', but will retry later. Error: [Errno 113] Connect call failed ('192.168.4.154', 80)
2021-04-13 08:33:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Current temperature -3.0°C
2021-04-13 08:33:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Inspect weather forecast from 2021-04-13 till 2021-04-21
2021-04-13 08:33:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Temperature vector: [-3.0, 5, -2, 8, -1, 14, 0, 15, 2, 18, 0, 12]
2021-04-13 08:33:53 DEBUG (MainThread) [custom_components.snowtire.binary_sensor] Too cold temperature detected!

**Additional context**
<!--
  Add any other context about the problem here.
-->
